name: Staging Deployment
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
    paths-ignore:
      - '*.md'
      - '*.rst'
  workflow_dispatch:
jobs:
  deploy:
    name: Staging Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update staging
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.STAGING_HOST }}
        username: root
        key: ${{ secrets.STAGING_KEY }}
        script_stop: true
        script: |
          cd /home/flaskuser/traveller
          git pull
          source venv/bin/activate
          pip install -r requirements/dev.txt
          cd traveller/
          python manage.py db migrate
          python manage.py db upgrade
          exit
          systemctl reload gunicorn-traveller.service
          echo "Done"
